language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - src/Client/node_modules

addons:
  chrome: stable

before_script:
  - cd src/Client  
  - npm install

script:
  - npm run lint
  - npm run test --watch=false
  - npm run build --prod
  - xvfb-run npm run e2e
