language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

addons:
  chrome: stable

cache:
  directories:
    - src/Client/node_modules

before_script:
  - cd src/Client
  - npm install

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod
  - ng e2e
